apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ml-platform-admin
  labels:
    app.kubernetes.io/name: ml-platform-admin
    app.kubernetes.io/part-of: ml-platform
rules:
  # Core resources
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["resourcequotas", "limitranges"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  
  # Apps resources
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["get", "list", "watch"]
  
  # Batch resources
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
  
  # Kubeflow resources
  - apiGroups: ["kubeflow.org"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  
  # Notebooks
  - apiGroups: ["kubeflow.org"]
    resources: ["notebooks"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  
  # Profiles
  - apiGroups: ["kubeflow.org"]
    resources: ["profiles"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  
  # Training jobs
  - apiGroups: ["kubeflow.org"]
    resources: ["pytorchjobs", "tfjobs", "mpijobs", "xgboostjobs", "paddlejobs"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  
  # Kueue resources
  - apiGroups: ["kueue.x-k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  
  # Metrics
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]







