apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-platform-admin
  namespace: ml-platform-admin
  labels:
    app.kubernetes.io/name: ml-platform-admin
    app.kubernetes.io/part-of: ml-platform







