apiVersion: v1
kind: ServiceAccount
metadata:
  name: enterprise-gateway-sa
  namespace: enterprise-gateway
  labels:
    app: enterprise-gateway
    app.kubernetes.io/name: enterprise-gateway
    app.kubernetes.io/part-of: kubeflow







