global:
  gpuSharing: true
  resourceReservation:
    appLabel: kai-rs
admission:
  gpuPodRuntimeClassName: nvidia-cdi
binder:
  cdiEnabled: true
  resourceReservation:
    runtimeClassName: nvidia-cdi
    appLabel: kai-rs
  additionalArgs:
    - "--feature-gates=DynamicResourceAllocation=false"
scheduler:
  additionalArgs:
    - "--feature-gates=DynamicResourceAllocation=false"







