apiVersion: v1
kind: Secret
metadata:
  name: coder-db-url
  namespace: coder
  labels:
    app.kubernetes.io/name: coder
    app.kubernetes.io/part-of: ml-platform
type: Opaque
stringData:
  url: "postgres://coder:coder@postgresql.coder.svc.cluster.local:5432/coder?sslmode=disable"
